
from datetime import datetime
import time
from collections import Counter
from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle

def section_heading(text, styles):
    p = Paragraph(f"<b>{text}</b>", styles["Heading2"])
    t = Table([[p]], colWidths=[6.4*inch])
    t.setStyle(TableStyle([
        ("BACKGROUND",(0,0),(-1,-1),colors.HexColor("#1E293B")),
        ("TEXTCOLOR",(0,0),(-1,-1),colors.white),
        ("LEFTPADDING",(0,0),(-1,-1),8),
        ("TOPPADDING",(0,0),(-1,-1),6),
        ("BOTTOMPADDING",(0,0),(-1,-1),6),
    ]))
    return t

def styled_table(data):
    t=Table(data,hAlign="LEFT")
    t.setStyle(TableStyle([
        ("BACKGROUND",(0,0),(-1,0),colors.HexColor("#1E293B")),
        ("TEXTCOLOR",(0,0),(-1,0),colors.white),
        ("GRID",(0,0),(-1,-1),0.5,colors.grey),
        ("BACKGROUND",(0,1),(0,-1),colors.HexColor("#EDF2F7")),
        ("BOTTOMPADDING",(0,0),(-1,-1),6),
        ("TOPPADDING",(0,0),(-1,-1),6),
        ("FONTNAME",(0,0),(-1,0),"Helvetica-Bold"),
    ]))
    return t

def generate_report(filename,dashboard):
    styles=getSampleStyleSheet()
    title=styles["Heading1"]; title.alignment=TA_CENTER
    sub=styles["Heading2"]; sub.alignment=TA_CENTER
    body=styles["BodyText"]
    doc=SimpleDocTemplate(filename)
    story=[]
    story.append(Paragraph("<b>MYCELIUM</b>",title))
    story.append(Paragraph("Network Threat Detection & Telemetry Platform",sub))
    story.append(Paragraph("<b>Security Monitoring Report</b>",sub))
    story.append(Spacer(1,0.25*inch))
    story.append(Paragraph(f"Generated: {datetime.now():%d %B %Y %H:%M:%S}",body))
    elapsed=int(time.time()-dashboard.start_time)
    uptime=f"{elapsed//3600:02}:{(elapsed%3600)//60:02}:{elapsed%60:02}"
    story.append(Paragraph(f"Monitoring Duration: {uptime}",body))
    story.append(Paragraph("Application Version: Mycelium v1.0.2",body))
    story.append(Spacer(1,0.3*inch))
    story.append(section_heading("Session Summary",styles)); story.append(Spacer(1,0.08*inch))
    story.append(styled_table([
        ["Metric","Value"],
        ["Packets Captured",f"{dashboard.packet_count:,}"],
        ["Threat Events",str(dashboard.alert_count)],
        ["Network Health",f"{dashboard.network_health}%"],
        ["Countries Reached",str(len(dashboard.map_countries))],
        ["External Hosts",str(len(dashboard.external_hosts))]
    ]))
    story.append(Spacer(1,0.25*inch))
    highs=sum(1 for e in dashboard.security_events if e["severity"]=="HIGH")
    meds=sum(1 for e in dashboard.security_events if e["severity"]=="MEDIUM")
    story.append(section_heading("Threat Summary",styles)); story.append(Spacer(1,0.08*inch))
    story.append(styled_table([
        ["Severity","Count"],
        ["HIGH",str(highs)],
        ["MEDIUM",str(meds)]
    ]))
    story.append(Spacer(1,0.25*inch))
    story.append(section_heading("Recent Security Findings",styles)); story.append(Spacer(1,0.08*inch))
    if dashboard.security_events:
        rows=[["Time","Severity","Application","Finding","Destination"]]
        for e in reversed(dashboard.security_events[-10:]):
            rows.append([e["timestamp"],e["severity"],e["process"],e["message"],e["destination"]])
        story.append(styled_table(rows))
    else:
        story.append(Paragraph("No security findings were detected during this monitoring session.",body))
    story.append(Spacer(1,0.25*inch))
    story.append(section_heading("Top Applications",styles)); story.append(Spacer(1,0.08*inch))
    apps=[["Application","Packets"]]
    for app,c in Counter(dashboard.application_stats).most_common(10):
        apps.append([app,str(c)])
    story.append(styled_table(apps))
    story.append(Spacer(1,0.25*inch))
    story.append(section_heading("Top Protocols",styles)); story.append(Spacer(1,0.08*inch))
    prots=[["Protocol","Packets"]]
    for p,c in Counter(dashboard.protocol_stats).most_common():
        prots.append([p,str(c)])
    story.append(styled_table(prots))
    story.append(Spacer(1,0.25*inch))
    story.append(section_heading("Overall Assessment",styles)); story.append(Spacer(1,0.08*inch))
    if highs:
        txt="One or more HIGH severity events were detected. Immediate review is recommended."
    elif meds:
        txt="Medium severity events were detected. Review the highlighted activity."
    else:
        txt="No suspicious activity was identified during this monitoring session."
    story.append(Paragraph(txt,body))
    story.append(Spacer(1,0.3*inch))
    story.append(Paragraph("<b>Generated by Mycelium v1.0.2</b>",body))
    story.append(Paragraph("Design and Evaluation of a Lightweight Real-Time Network Threat Detection and Telemetry Platform",body))
    doc.build(story)
